//Allphotos taken by Severin Candrian
//unsplash.com/@feeypflanzen
// https://unsplash.com/photos/leLyXEKXjMY

export const storeProducts = [
  {
    id: 1,
    title: "Giant Taro",
    sciName: "Alocasia Macrorrhiza",
    family: "Araceae",
    species: "Araceae",
    img: "img/Alocasia-Macrorrhiza.jpg",
    price: 50,
    info: "Alocasia macrorrhizos is a species of flowering plant in the arum family that it is native to rainforests of Island Southeast Asia, New Guinea, and Queensland and has long been cultivated in the Philippines, many Pacific islands, and elsewhere in the tropics.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Goeppertia insignis",
    sciName: "Calathea Lancifolia",
    family: "Marantaceae",
    species: "G. insignis",
    img: "img/Calathea-lancifolia.jpg",
    price: 45,
    info: "Goeppertia insignis, the rattlesnake plant, is a species of flowering plant in the Marantaceae family, native to Rio de Janeiro state in Brazil. It is an evergreen perennial, growing to 60–75 cm, with slender pale green leaves to 45 cm, heavily marked above with dark blotches, purple below.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Dracaena Fragrans",
    sciName: "Dracaena Fragrans",
    family: "Asparagaceae",
    species: "D. fragrans",
    img: "img/Dracaena-Fragrans.jpg",
    price: 39.99,
    info: "Dracaena fragrans, is a flowering plant species that is native throughout tropical Africa, from Sudan south to Mozambique, west to Côte d'Ivoire and southwest to Angola, growing in upland regions at 600–2,250 m altitude. It is also known as striped dracaena, compact dracaena, and corn plant.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Rubber fig",
    sciName: "Ficus elastica variegata",
    family: "Moraceae",
    species: "F. elastica",
    img: "img/Ficus-elastica-variegata.jpg",
    price: 57.5,
    info: "Ficus elastica, the rubber fig, rubber bush, rubber tree, rubber plant, or Indian rubber bush, Indian rubber tree, is a species of plant in the fig genus, native to eastern parts of South Asia and southeast Asia. It has become naturalized in Sri Lanka, the West Indies, and the US State of Florida.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Swiss cheese plant",
    sciName: "Monstera",
    family: "Araceae",
    species: "M. deliciosa",
    img: "img/Monstera.jpg",
    price: 52.99,
    info: "Monstera deliciosa, the Swiss cheese plant, is a species of flowering plant native to tropical forests of southern Mexico, south to Panama. It has been introduced to many tropical areas, and has become a mildly invasive species in Hawaii, Seychelles, Ascension Island and the Society Islands.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Monstera minima",
    sciName: "Monstera Minima Trellis",
    family: "Araceae",
    species: "M. deliciosa",
    img: "img/Monstera-Minima.jpg",
    price: 69.99,
    info: "Monstera Minima Trellis is a fast growing vining plant, sought after for its unique fenestrated leaves. They resemble the Monstera deliciosa. The leaves are similarly split with “windows,” but stay quite small. This plant is easy to care for, and loves to climb up a moss pole.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Peace Lily",
    sciName: "Spathiphyllum",
    family: "Araceae",
    species: "monocotyledonous fl",
    img: "img/Peace-Lily.jpg",
    price: 48.5,
    info: "Peace lilies (Spathiphyllum), also known as closet plants, are a popular choice for offices and homes. When it comes to indoor plants, peace lily plants are some of the easiest to care for. However, while peace lily plant care is easy, proper growing conditions are still important. Let’s take a look at the care of peace lilies.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Philodendron",
    sciName: "Philodendron",
    family: "Araceae",
    species: "Aroideae",
    img: "img/Philodendron.jpg",
    price: 35.0,
    info: "Philodendron is a large genus of flowering plants in the family Araceae. As of September 2015, the World Checklist of Selected Plant Families accepted 489 species; other sources accept different numbers.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "verrucosum",
    sciName: "Philodendron verrucosum",
    family: "Araceae",
    species: "P. verrucosum",
    img: "img/Philodendron-verrucosum.jpg",
    price: 55.0,
    info: "Trichophyton verrucosum, commonly known as the cattle ringworm fungus, is a dermatophyte largely responsible for fungal skin disease in cattle, but is also a common cause of ringworm in donkeys, dogs, goat, sheep, and horses. ",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Polyscias",
    sciName: "Polyscias guilfoylei",
    family: "Araliaceae",
    species: "P. acuminata",
    img: "img/Polyscias.jpg",
    price: 33.0,
    info: "Polyscias is a genus of flowering plants in the family Araliaceae. They bear pinnately compound leaves. In 2003, a checklist and nomenclator was published for Araliaceae. In this work, 116 species were listed for Polyscias.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Scindapsus",
    sciName: "Alismatales",
    family: "Araceae",
    species: "Monstereae",
    img: "img/Scindapsus.jpg",
    price: 39.5,
    info: "Scindapsus is a genus of flowering plants in the family Araceae. It is native to Southeast Asia, New Guinea, Queensland, and a few western Pacific islands. The species Scindapsus pictus is common in cultivation. Scindapsus is not easily distinguishable from Epipremnum.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Zanzibar Gem",
    sciName: "Zamioculcas-Zamiifolia",
    family: "Araceae",
    species: "Z. zamiifolia",
    img: "img/Zamioculcas-Zamiifolia.jpg",
    price: 55.0,
    info: "Zamioculcas is a genus of flowering plants in the family Araceae, containing the single species Zamioculcas zamiifolia. It is a tropical perennial plant native to eastern Africa, from southern Kenya to northeastern South Africa.",
    inCart: false,
    count: 0,
    total: 0,
  },
];
